stages:
  - determine
  - build
  - tag
  - push

variables:
  IMAGE_NAME: "amoljorewar/shift-roster-app"
  DOCKER_TLS_CERTDIR: ""  # Disable TLS for Docker-in-Docker
  DOCKER_HOST: "tcp://docker:2375"

services:
  - docker:dind  # Enable Docker-in-Docker for building and pushing images

before_script:
  # Ensure jq is installed (shared runners may not have it pre-installed)
  - apt-get update && apt-get install -y jq || echo "jq is already installed"

determine_tags:
  stage: determine
  script:
    - >
      LATEST_TAG=$(curl -s -u "$DOCKER_HUB_USERNAME:$DOCKER_HUB_PASSWORD" https://hub.docker.com/v2/repositories/$IMAGE_NAME/tags/?page_size=1 | jq -r '.results[0].name')
    - echo "Latest tag found."
    - >
      if [[ $LATEST_TAG =~ ^v([0-9]+)\.([0-9]+)$ ]]; then
        MAJOR=${BASH_REMATCH[1]}
        MINOR=${BASH_REMATCH[2]}
        NEW_TAG="v$MAJOR.$((MINOR + 1))"
      else
        echo "No valid tag found, defaulting to v1.0"
        NEW_TAG="v1.0"
      fi
    - echo "New tag for previous image."
    - echo $LATEST_TAG > .previous_tag
    - echo $NEW_TAG > .new_versioned_tag
    - echo "latest" > .latest_tag
  artifacts:
    paths:
      - .latest_tag
      - .previous_tag
      - .new_versioned_tag

build_image:
  stage: build
  image: docker:20.10  # Use an image with Docker CLI pre-installed
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""  # Disable Docker-in-Docker TLS
    DOCKER_HOST: "tcp://docker:2375"  # Ensure the CLI communicates with the Docker daemon
  dependencies:
    - determine_tags
  script:
    - cat .latest_tag
    - LATEST_TAG=$(cat .latest_tag)
    - echo "Building Docker image with tag."
    - docker build -t $IMAGE_NAME:$LATEST_TAG .
  artifacts:
    paths:
      - .latest_tag

tag_previous_image:
  stage: tag
  image: docker:20.10
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  script:
    # Use GitLab registry credentials for login
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$DOCKER_REGISTRY" --password-stdin || { echo 'Login failed'; exit 1; }

    # Re-tagging and pushing the image
    - PREVIOUS_TAG=$(cat .previous_tag)
    - NEW_VERSIONED_TAG=$(cat .new_versioned_tag)
    - |
      if [[ -n "$PREVIOUS_TAG" && "$PREVIOUS_TAG" != "null" ]]; then
        echo "Re-tagging $IMAGE_NAME:$PREVIOUS_TAG to $IMAGE_NAME:$NEW_VERSIONED_TAG"
        docker pull $IMAGE_NAME:$PREVIOUS_TAG
        docker tag $IMAGE_NAME:$PREVIOUS_TAG $IMAGE_NAME:$NEW_VERSIONED_TAG
        docker push $IMAGE_NAME:$NEW_VERSIONED_TAG
      fi

push_images:
  stage: push
  image: docker:20.10  # Make sure the Docker CLI is available in this stage
  dependencies:
    - determine_tags
    - build_image
    - tag_previous_image
  script:
    - LATEST_TAG=$(cat .latest_tag)
    - NEW_VERSIONED_TAG=$(cat .new_versioned_tag)
    - echo "Pushing image with tag."
    - docker push $IMAGE_NAME:$LATEST_TAG
    - >
      if [[ -n "$NEW_VERSIONED_TAG" ]]; then
        echo "Pushing versioned tag: $IMAGE_NAME:$NEW_VERSIONED_TAG"
        docker push $IMAGE_NAME:$NEW_VERSIONED_TAG
      fi
